---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: localhost
  connection: local
  vars_files:
  - "../vars/quagga.yml"
  roles:
   - { role: "lxc_hosts" }

- name: Create quagga container
  hosts: all_containers
  gather_facts: false
  user: root
  roles:
   - { role: "lxc_container_create" }

- hosts: quagga_container
  connection: remote
  vars_files:
  - "../vars/quagga.yml"

  roles:
   - role: configure-quagga
