#!/bin/bash

if [[ $DEPLOY_SCENARIO == "os-odl-bgpvpn" ]] && [[ $XCI_FLAVOR == "ha" ]]; then
    export VM_MEMORY_SIZE=20480
elif [[ $DEPLOY_SCENARIO == "os-odl-bgpvpn" ]]; then
    export VM_MEMORY_SIZE=16384
fi